site_name: LA Metro Digital Services Team Docs
repo_url: https://github.com/LACMTA/digital-services-team-docs/

theme: 
  font:
    text: Open Sans
  favicon: media/favicon.png
  logo: media/favicon-reverse.png
  palette:
    primary: black
  name: material
  custom_dir: overrides
  features:
      - navigation.instant
      - navigation.tabs
      - content.code.annotate
      - search.highlight
      - toc.integrate
      - navigation.indexes
      - navigation.top
      
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
    # - pymdownx.highlight:
    #     linenums: true
    - pymdownx.superfences
    - pymdownx.magiclink
    - smarty
    - meta
    - toc:
        permalink: True
        toc_depth: 2
    - sane_lists
    - admonition
    - footnotes
    - attr_list
    
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css

edit_uri: edit/main/docs/
plugins:
  - git-revision-date
  - autorefs
  - table-reader
  - macros
  - search:
      lang: en
  # - htmlproofer
      # raise_error: True
  - encryptcontent:
      title_prefix: '🔒'
      # global_password: !ENV METRO_DOCS_PASS
      # password_button: True      
      encrypted_something:
          mkdocs-encrypted-toc: [nav, class]
          mkdocs-encrypted-footer: [div, id]
          mkdocs-encrypted-footer-meta: [div, id]