name: ci 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
        env:
          METRO_DOCS_PASS: ${{ secrets.METRO_DOCS_PASS }}
      - run: pip install mkdocs-material
      - run: pip install mkdocs-encryptcontent-plugin
      - run: pip install mkdocs-git-revision-date-plugin
      - run: pip install mkdocs-autorefs
      - run: mkdocs gh-deploy --force
        env:
          METRO_DOCS_PASS: ${{secrets.METRO_DOCS_PASS}}
