# This is a basic workflow to help you get started with Actions

name: pull from dev to main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
#   push:
#     branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          
jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.3.1
      with:
        stable_branch: 'main'
        development_branch: 'dev'
        allow_ff: false
        allow_fork: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
